# Docker Compose file for GeoCaching Bot

services:
  geocaching-bot:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: geocaching-bot
    restart: unless-stopped
    
    # Переменные окружения (загружаются из .env файла хоста)
    env_file:
      - .env
    
    # Переменные с значениями по умолчанию для Docker
    environment:
      - DATABASE_PATH=${DATABASE_PATH:-/app/data/geocaching.db}
      - LIVE_LOCATION_DURATION_HOURS=${LIVE_LOCATION_DURATION_HOURS:-1}
      - TARGET_DISTANCE_METERS=${TARGET_DISTANCE_METERS:-200}
      - UPDATE_INTERVAL_SECONDS=${UPDATE_INTERVAL_SECONDS:-5}
    
    # Монтируем тома для персистентности данных
    volumes:
      - geocaching_data:/app/data        # База данных SQLite
      - ./logs:/app/logs:rw             # Логи (опционально)
    
    # Для мониторинга состояния контейнера
    healthcheck:
      test: ["CMD", "pgrep", "-f", "geocaching-bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Лимиты ресурсов
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
    
    # Лог конфигурация
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Именованные тома для персистентности данных
volumes:
  geocaching_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

# Сеть для изоляции (опционально)
networks:
  default:
    name: geocaching-network
    driver: bridge 